name: "이슈 생성"
description: 타입을 선택하고 이슈를 작성합니다.
title: "[] "
body:
  - type: dropdown
    id: type
    attributes:
      label: 타입(라벨)
      description: 아래 중 하나를 선택하세요. (선택값으로 라벨을 자동 적용하려면 아래 Actions 옵션을 추가하세요)
      options:
        - feat
        - chore
        - docs
        - build
        - test
        - refactor
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: 요약
      description: 무엇을 할지/무슨 문제인지 한 줄 요약
      placeholder: 예) 지도 마커 hover 시 PreviewCard 위치가 흔들림
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: 상세 내용
      description: 배경, 맥락, 현재 상태를 적어주세요
      placeholder: |
        - 배경:
        - 현재 상태:
        - 참고:
    validations:
      required: false

  - type: textarea
    id: tasks
    attributes:
      label: 작업 체크리스트
      placeholder: |
        - [ ] 할 일 1
        - [ ] 할 일 2
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: 참고 자료
      placeholder: |
        - 링크:
        - 스크린샷/로그:
    validations:
      required: false
